Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('answer/', include('front.urls')),
    path('', include('main.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from . import views
from django.urls import path

app_name = 'dash'

urlpatterns = [
    path('', views.main, name = 'main'),
    #quiz create
    path('create-quizz', views.create_quiz, name = 'quiz_create'),
    path('create-question/<int:id>', views.create_question , name ='quest_create' ),
    #quiz & questions detials
    path('questions/<int:id>', views.questions_list, name = 'questions'),
    path('question-detail/<int:id>', views.quest_detail, name = 'quest_detail'),
    path('quiz-delete/<int:id>', views.quiz_delete , name ='quiz_delete' ),
    path('get-results/<int:id>', views.get_results , name ='get_results' ),
    path('result-detail/<int:id>', views.result_detail , name ='result_detail' ),
    #auth
    path('login', views.logging_in, name = 'login'),
    path('register', views.register, name = 'register'),
]

templates/quiz/create-question.html
{%extends 'base.html'%}
  {%block content%}

    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-xl-3"></div>
            <div class="card col-xl-6 col-lg-6 " id="sample-login">
                <form method = 'post'> {%csrf_token%}
                <div class="card-header justify-content-center d-flex">
                    <h4>Question</h4>
                </div>
                <div class="card-body pb-0">
                    <div class="form-group">
                    <label>write down a question</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                        <div class="input-group-text">
                            <i class="fa-solid fa-question"></i>
                        </div>
                        </div>
                        <input type="text" class="form-control" placeholder="Quiz name" name = 'title'>
                    </div>
                    </div>
                    <br>
                    <div class="form-group">
                        <h6 style="text-align: center;">write down correct answers</h6>
                        <label for="#">give a correct answer for that field, and we randomly place the answer for each test takers.</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa-solid fa-check"></i>
                            </div>
                            </div>
                            <input type="text" class="form-control" placeholder="Correct answer for the question " name="correct">
                        </div>
                    </div>
                    <br>
                    <div class="form-group">
                        <h6 style="text-align: center;">Give 3 wrong answers</h6>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa-regular fa-circle-xmark"></i>
                            </div>
                            </div>
                            <input type="text" class="form-control" placeholder="1st Wrong answer for the question " name = 'incorrect1'>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa-regular fa-circle-xmark"></i>
                            </div>
                            </div>
                            <input type="text" class="form-control" placeholder="2nd Wrong answer for the question " name="incorrect2">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa-regular fa-circle-xmark"></i>
                            </div>
                            </div>
                            <input type="text" class="form-control" placeholder="3rd Wrong answer for the question " name = 'incorrect3'>
                        </div>
                    </div>
                    <div class="form-group mb-0">
                    </div>
                    <div class="card-footer  justify-content-left d-flex">
                        <div class="col-6">
                            <button  type="submit" name="submit_action" value="exit" class="btn btn-danger">Save & Exit</button>
                        </div>
                        <div class="col-6">
                            <button type="submit" name="submit_action" value="save_again" class="btn btn-primary">Save & add question</button>
                        </div>
                    </div>
                </div>
                
                </form>
            </div>
        </div>
    </div>

  {%endblock%}

templates/quiz/create-quiz.html
{% extends 'base.html' %}
{% block content %}
<div style="margin-top: 100px;"></div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-xl-3"></div>
      <div class="card col-xl-6 col-lg-6" id="sample-login">
        <form method="post"> {% csrf_token %}
          <div class="card-header">
            <h4>QUIZ</h4>
          </div>
          <div class="card-body pb-0">
            <p class="text-muted">Give a name for this quiz</p>
            <div class="form-group">
              <label>Name</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <div class="input-group-text">
                    <i class="fa-solid fa-question"></i>
                  </div>
                </div>
                <textarea id="editor"></textarea>

              </div>
            </div>
            <div class="form-group">
              <label>Start Time</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <div class="input-group-text">
                    <i class="fa-solid fa-clock"></i>
                  </div>
                </div>
                <input type="datetime-local" class="form-control" name="start_time" required>
              </div>
            </div>
            <div class="form-group">
              <label>End Time</label>
              <div class="input-group">
                <div class="input-group-prepend">
                  <div class="input-group-text">
                    <i class="fa-solid fa-clock"></i>
                  </div>
                </div>
                <input type="datetime-local" class="form-control" name="end_time" required>
              </div>
            </div>
          </div>
          <div class="card-footer justify-content-center d-flex">
            <button type="submit" class="btn btn-primary">Next</button>
          </div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

templates/quiz/result-detail.html
{%extends 'base.html'%}
  {%block content%}
      <!-- Main Content -->

        <section class="section" >
          
          <div class="row d-flex justify-content-center">
            <h1 class="col-12" style="text-align: center;">Javoblar</h1>
          <div class="col-12 col-md-10 col-lg-10">
            <div class="card">
                <div class="d-flex justify-content-around">
                    <p>{{taker.full_name}}</p>
                    <p><a href="tel:{{taker.phone}}">{{taker.phone}}</a></p>
                    <p><a href="mailto:">{{taker.email}}</a></p>
                </div>
              <div class="card-body p-0">
                <div class="table-responsive">
                  <table class="table table-striped table-md">
                    <tbody><tr>
                      <th>#</th>
                      <th>Savol</th>
                      <th>To`g`ri javob</th>
                      <th>Belgilagan javob</th>
                      <th>Natija</th>
                    </tr>
                    {% for answer in answers %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td>{{answer.question.title}}</td>
                      <td>{{answer.question.correct_answer.name}}</td>
                      <td>{{answer.answer.name}}</td>
                      {% if answer.is_correct %}
                        <td><div class="badge badge-success">To`g`ri</div></td>
                      {% else %}
                        <td><div class="badge badge-danger">Xato</div></td>
                      {% endif %}
                    </tr>
                    {% endfor %}
                    <!-- <tr>
                      <td>5</td>
                      <td>Isnap Kiswandi</td>
                      <td>2017-01-17</td>
                      <td>
                        <div class="badge badge-success">Active</div>
                      </td>
                      <td><a href="#" class="btn btn-primary">Detail</a></td>
                    </tr> -->
                  </tbody></table>
                </div>
              </div>
            </div>
          </div>
        </div>
        </section>
        <div class="settingSidebar">
          <a href="javascript:void(0)" class="settingPanelToggle"> <i class="fa fa-spin fa-cog"></i>
          </a>
          <div class="settingSidebar-body ps-container ps-theme-default">
            <div class=" fade show active">
              <div class="setting-panel-header">Setting Panel
              </div>
              <div class="p-15 border-bottom">
                <h6 class="font-medium m-b-10">Select Layout</h6>
                <div class="selectgroup layout-color w-50">
                  <label class="selectgroup-item">
                    <input type="radio" name="value" value="1" class="selectgroup-input-radio select-layout" checked>
                    <span class="selectgroup-button">Light</span>
                  </label>
                  <label class="selectgroup-item">
                    <input type="radio" name="value" value="2" class="selectgroup-input-radio select-layout">
                    <span class="selectgroup-button">Dark</span>
                  </label>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <h6 class="font-medium m-b-10">Sidebar Color</h6>
                <div class="selectgroup selectgroup-pills sidebar-color">
                  <label class="selectgroup-item">
                    <input type="radio" name="icon-input" value="1" class="selectgroup-input select-sidebar">
                    <span class="selectgroup-button selectgroup-button-icon" data-toggle="tooltip"
                      data-original-title="Light Sidebar"><i class="fas fa-sun"></i></span>
                  </label>
                  <label class="selectgroup-item">
                    <input type="radio" name="icon-input" value="2" class="selectgroup-input select-sidebar" checked>
                    <span class="selectgroup-button selectgroup-button-icon" data-toggle="tooltip"
                      data-original-title="Dark Sidebar"><i class="fas fa-moon"></i></span>
                  </label>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <h6 class="font-medium m-b-10">Color Theme</h6>
                <div class="theme-setting-options">
                  <ul class="choose-theme list-unstyled mb-0">
                    <li title="white" class="active">
                      <div class="white"></div>
                    </li>
                    <li title="cyan">
                      <div class="cyan"></div>
                    </li>
                    <li title="black">
                      <div class="black"></div>
                    </li>
                    <li title="purple">
                      <div class="purple"></div>
                    </li>
                    <li title="orange">
                      <div class="orange"></div>
                    </li>
                    <li title="green">
                      <div class="green"></div>
                    </li>
                    <li title="red">
                      <div class="red"></div>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <div class="theme-setting-options">
                  <label class="m-b-0">
                    <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input"
                      id="mini_sidebar_setting">
                    <span class="custom-switch-indicator"></span>
                    <span class="control-label p-l-10">Mini Sidebar</span>
                  </label>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <div class="theme-setting-options">
                  <label class="m-b-0">
                    <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input"
                      id="sticky_header_setting">
                    <span class="custom-switch-indicator"></span>
                    <span class="control-label p-l-10">Sticky Header</span>
                  </label>
                </div>
              </div>
              <div class="mt-4 mb-4 p-3 align-center rt-sidebar-last-ele">
                <a href="#" class="btn btn-icon icon-left btn-primary btn-restore-theme">
                  <i class="fas fa-undo"></i> Restore Default
                </a>
              </div>
            </div>
          </div>
        </div>

  {%endblock%}

templates/quiz/results.html
{%extends 'base.html'%}
  {%block content%}
      <!-- Main Content -->

        <section class="section" >
          
          <div class="row d-flex justify-content-center">
            <h1 class="col-12" style="text-align: center;">All quizes you've created</h1>
          {% for result in results %}
         
          <div class="card card-danger col-5 m-2">
            <div class="card-header">
              <h4>{{result.taker.full_name}}</h4>
              <div class="card-header-action">
                <a href="{% url 'dash:result_detail' result.id %}" class="btn btn-primary">Get Details</a>
              </div>
            </div>
            <div class="card-body">
            </div>
            <p>Total questions {{result.questions}}</p>
            <p>Correct answers {{result.correct_answers}}</p>
            <p>In Correct answers {{result.incorrect_answers}}</p>
            <p>Percentage {{result.percentage}} %</p>
            </div>

          {%endfor%}
        </div>
        </section>
        <div class="settingSidebar">
          <a href="javascript:void(0)" class="settingPanelToggle"> <i class="fa fa-spin fa-cog"></i>
          </a>
          <div class="settingSidebar-body ps-container ps-theme-default">
            <div class=" fade show active">
              <div class="setting-panel-header">Setting Panel
              </div>
              <div class="p-15 border-bottom">
                <h6 class="font-medium m-b-10">Select Layout</h6>
                <div class="selectgroup layout-color w-50">
                  <label class="selectgroup-item">
                    <input type="radio" name="value" value="1" class="selectgroup-input-radio select-layout" checked>
                    <span class="selectgroup-button">Light</span>
                  </label>
                  <label class="selectgroup-item">
                    <input type="radio" name="value" value="2" class="selectgroup-input-radio select-layout">
                    <span class="selectgroup-button">Dark</span>
                  </label>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <h6 class="font-medium m-b-10">Sidebar Color</h6>
                <div class="selectgroup selectgroup-pills sidebar-color">
                  <label class="selectgroup-item">
                    <input type="radio" name="icon-input" value="1" class="selectgroup-input select-sidebar">
                    <span class="selectgroup-button selectgroup-button-icon" data-toggle="tooltip"
                      data-original-title="Light Sidebar"><i class="fas fa-sun"></i></span>
                  </label>
                  <label class="selectgroup-item">
                    <input type="radio" name="icon-input" value="2" class="selectgroup-input select-sidebar" checked>
                    <span class="selectgroup-button selectgroup-button-icon" data-toggle="tooltip"
                      data-original-title="Dark Sidebar"><i class="fas fa-moon"></i></span>
                  </label>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <h6 class="font-medium m-b-10">Color Theme</h6>
                <div class="theme-setting-options">
                  <ul class="choose-theme list-unstyled mb-0">
                    <li title="white" class="active">
                      <div class="white"></div>
                    </li>
                    <li title="cyan">
                      <div class="cyan"></div>
                    </li>
                    <li title="black">
                      <div class="black"></div>
                    </li>
                    <li title="purple">
                      <div class="purple"></div>
                    </li>
                    <li title="orange">
                      <div class="orange"></div>
                    </li>
                    <li title="green">
                      <div class="green"></div>
                    </li>
                    <li title="red">
                      <div class="red"></div>
                    </li>
                  </ul>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <div class="theme-setting-options">
                  <label class="m-b-0">
                    <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input"
                      id="mini_sidebar_setting">
                    <span class="custom-switch-indicator"></span>
                    <span class="control-label p-l-10">Mini Sidebar</span>
                  </label>
                </div>
              </div>
              <div class="p-15 border-bottom">
                <div class="theme-setting-options">
                  <label class="m-b-0">
                    <input type="checkbox" name="custom-switch-checkbox" class="custom-switch-input"
                      id="sticky_header_setting">
                    <span class="custom-switch-indicator"></span>
                    <span class="control-label p-l-10">Sticky Header</span>
                  </label>
                </div>
              </div>
              <div class="mt-4 mb-4 p-3 align-center rt-sidebar-last-ele">
                <a href="#" class="btn btn-icon icon-left btn-primary btn-restore-theme">
                  <i class="fas fa-undo"></i> Restore Default
                </a>
              </div>
            </div>
          </div>
        </div>

  {%endblock%}