Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('answer/', include('front.urls')),
    path('', include('main.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from . import views
from django.urls import path

app_name = 'dash'

urlpatterns = [
    path('', views.main, name = 'main'),
    #quiz create
    path('create-quizz', views.create_quiz, name = 'quiz_create'),
    path('create-question/<int:id>', views.create_question , name ='quest_create' ),
    #quiz & questions detials
    path('questions/<int:id>', views.questions_list, name = 'questions'),
    path('question-detail/<int:id>', views.quest_detail, name = 'quest_detail'),
    path('quiz-delete/<int:id>', views.quiz_delete , name ='quiz_delete' ),
    path('get-results/<int:id>', views.get_results , name ='get_results' ),
    path('result-detail/<int:id>', views.result_detail , name ='result_detail' ),
    #auth
    path('login', views.logging_in, name = 'login'),
    path('register', views.register, name = 'register'),
]

templates/details/detail.html
{%extends 'base.html'%}
  {%block content%}

    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-xl-3"></div>
            <div class="card col-xl-6 col-lg-6 " id="sample-login">
                <form method = 'post'> {%csrf_token%}
                <div class="card-header justify-content-center d-flex">
                    <h4>Question detail</h4>
                </div>
                <div class="card-body pb-0">
                    <div class="form-group">
                    <label>the question</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                        <div class="input-group-text">
                            <i class="fa-solid fa-question"></i>
                        </div>
                        </div>
                        <input type="text" class="form-control" placeholder="Question title" name = 'title' value = "{{question.title}}" >
                    </div>
                    </div>
                    <br>
                    <div class="form-group">
                        <label for="#">Correct answer</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa-solid fa-check"></i>
                            </div>
                            </div>
                            <input type="text" class="form-control" placeholder="Correct answer for the question " name="correct" value="{{option_correct.name}}">
                        </div>
                    </div>
                    <br>
                    <label for="#">incorrect options</label>
                    {%for incorrect in options%}
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="fa-regular fa-circle-xmark"></i>
                            </div>
                            </div>
                            <input type="text" class="form-control" placeholder=" Wrong answer for the question " name="incorrect{{forloop.counter}}" value="{{incorrect.name}}">
                        </div>
                    </div>
                    {%endfor%}
                    <div class="form-group mb-0">
                    </div>
                    <div class="card-footer  justify-content-left d-flex">
                        <div class="col-12 d-flex justify-content-center">
                            <button type="submit" name="submit_action" value="save_again" class="col-12 btn btn-primary">Save if changed</button>
                        </div>
                    </div>
                </div>
                
                </form>
            </div>
        </div>
    </div>

  {%endblock%}

templates/details/questions.html
{%extends 'base.html'%}
  {%block content%}
  <div class="col-12 col-md-12 col-lg-12">
    <div class="card">
      <div class="card-header">
        <h4>Simple Table</h4>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered table-md">
            <tbody><tr>
              <th>No</th>
              <th>Name</th>
              <th>Action</th>
            </tr>
            <tr>
                {%for question in questions%}
              <td>{{forloop.counter}}</td>
              <td>{{question.title }}</td>
              <td><a href="{%url 'dash:quest_detail' question.id%}" class="btn btn-primary">Detail</a></td>
            </tr>
            {%endfor%}
          </tbody></table>
        </div>
      </div>
    </div>
  </div>
  {%endblock%}