Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('answer/', include('front.urls')),
    path('', include('main.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/urls.py
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('quiz/<str:code>', views.quiz_detail, name='quiz_detail'),
    path('create-answer/<str:code>/', views.create_answers, name='create_answers'),
]

main/urls.py
from . import views
from django.urls import path

app_name = 'dash'

urlpatterns = [
    path('', views.main, name = 'main'),
    #quiz create
    path('create-quizz', views.create_quiz, name = 'quiz_create'),
    path('create-question/<int:id>', views.create_question , name ='quest_create' ),
    #quiz & questions detials
    path('questions/<int:id>', views.questions_list, name = 'questions'),
    path('question-detail/<int:id>', views.quest_detail, name = 'quest_detail'),
    path('quiz-delete/<int:id>', views.quiz_delete , name ='quiz_delete' ),
    path('get-results/<int:id>', views.get_results , name ='get_results' ),
    path('result-detail/<int:id>', views.result_detail , name ='result_detail' ),
    #auth
    path('login', views.logging_in, name = 'login'),
    path('register', views.register, name = 'register'),
]

front/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from main import models
from django.utils  import timezone

def create_result(id):
    quiz_taker = models.QuizTaker.objects.get(id=id)
    correct = 0
    incorrect = 0
    for object in models.Answer.objects.filter(taker=quiz_taker):
        if object.is_correct:
            correct +=1
        else:
            incorrect +=1

    models.Result.objects.create(
        taker=quiz_taker,
        correct_answers=correct,
        incorrect_answers=incorrect
    )

def quiz_detail(request, code):
    quiz = models.Quiz.objects.get(code=code)
    quiz_taker = models.QuizTaker.objects.filter(quiz=quiz).first()
    
    # Check if quiz_taker is None before using it
    if not quiz_taker:
        return HttpResponse("Quiz taker not found")
    
    result = models.Result.objects.filter(taker=quiz_taker).first()
    questions = models.Question.objects.filter(
        quiz=quiz
    )
    now = timezone.now()
    
    if quiz.start_time and now < quiz.start_time:
        return HttpResponse("Quiz hali boshlanmagan")
    elif quiz.end_time and now > quiz.end_time:
        return HttpResponse("Quiz tugagan")
    
    context = {
        'quiz': quiz,
        'questions': questions,
        'result': result
    }
    return render(request, 'front/quiz-detail.html', context)



def create_answers(request, code):
    quiz = models.Quiz.objects.get(code=code)
    full_name = request.POST['full_name']
    phone = request.POST['phone']
    email = request.POST.get('email')
    quiz_taker = models.QuizTaker.objects.create(
        full_name=full_name,
        phone=phone,
        email=email,
        quiz=quiz
    )
    for key, value in request.POST.items():
        if key.isdigit():
            models.Answer.objects.create(
                taker=quiz_taker,
                question_id=int(key),
                answer_id=int(value)
            )
    create_result(quiz_taker.id)
    return redirect('dash:result_detail', id=quiz_taker.id)

templates/front/quiz-detail.html
{% extends 'base.html' %}
  {% block content %}
  <section class="section">
    <div class="section-body">
      <div class="row">
        <div class="col-12 col-md-12 col-lg-12">
          <div class="card">
            <form action="{% url 'front:create_answers' quiz.code %}" method="post">
                {% csrf_token %}
                <div class="card-header">
                  <h4>{{quiz.title}}</h4>
                </div>
                <div class="card-body">
                  <div>
                      <label for="name">FISh</label>
                      <input class="form-control" type="text" id="name" name="full_name" required>
                  </div>
                  <div>
                      <label for="name">Phone</label>
                      <input class="form-control" type="text" id="phone" name="phone" required>
                  </div>
                  <div>
                      <label for="name">Email</label>
                      <input class="form-control" type="email" id="email" name="email">
                  </div>
                    {% for question in questions %}
                    <div class="section-title">{{forloop.counter}}) {{question.title}}</div>
                        {% for option in question.get_options %}
                        <div class="custom-control custom-radio">
                            <input type="radio" id="option{{option.id}}" name="{{question.id}}" class="custom-control-input" required value="{{option.id}}">
                            <label class="custom-control-label" for="option{{option.id}}">{{option.name}}</label>
                        </div>
                        {% endfor %} <hr>
                    <!-- <div class="custom-control custom-radio">
                        <input type="radio" id="customRadio4" name="customRadio" class="custom-control-input">
                        <label class="custom-control-label" for="customRadio4">Or toggle this other custom radio</label>
                    </div> -->
                    {% endfor %}
                    <a href="{% url 'dash:result_detail' result.id %}">
                    <button class="btn btn-success">Yuborish</button>
                  </a>
                </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}